### ISSUE TITLE
Refactor Project Structure

### ISSUE THREAD

**Issue by fercevik729** [fercevik729/UCSC-Course-Planner#214]

**Comment by zacktraczyk** [comment]
Howdy, excited to be working on the project this quarter with the CSE115 b/c group. You mentioned in the meeting that you may want some input on the refactor. Looking over the code I have some thoughts on the codebase as a fresh pair of eyes.

Although, I would like to acknowledge I have not touched any code in this project so I may not have a full idea of why certain decisions / tradeoffs are being made and therefore you are more than welcome to ignore any and all input.

## Big Refactor Options

### Next12 -> Next13

So far your separation between JSX / non JSX elements is really well defined (e.g. dedicated contexts/hooks/types folders). Seems like the code would benefit from breaking up your components folder to differentiate reusable components from unique views. Using [Next13's App router](https://nextjs.org/docs/app) would be excellent for this. It enforces a project structure through routing and provides a clean abstraction for loading and error states. I also remember someone mentioning a desire to use more NextJS features like SSR, and the app router greatly simplifies the use of server components.

The problem is this is a fundamental change in how the codebase works / is structured, and would be a giant refactor. It is possible to [incrementally updated to the app router](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration) but I could definitely see a case for why this would not be the best move, especially as Next13 only became stable in September.

#### Alternative to Next Migration

Another option for changing the file structure without changing Next versions would be to create a separate views folder, that was structured similar to the app router. It would be more intuitive if the codebase was structured in a way that represented page / navigation structure.

### MUI -> ShadCN

This one is in part a personal preference, so definitely take it with a grain of salt 😅. Another big refactor item would be replacing MUI with an internal / more customizable component library. MUI is super great for getting battle tested accessible components, but it comes at the cost of performance and big initial JS bundles. If possible it would be great to have ownership over component styling for the sake of performance and customizability. [ShadCN](https://ui.shadcn.com/) is a great solution that removes the work of component creation while giving you full code ownership. There are other such component libraries like TailwindUI that give you this control.

A big downside is that the frontend developers than are trusted to insure these components are responsive, accessible, and good looking so I understand why this may not be the best direction to go.

## Smaller Additions

### Responsive Layouts

I noticed the screen gives a warning as the width becomes small, it would be great to have responsive layouts that include half sized screens and mobile.

### Loading States

Loading states would be a great UI/UX improvement as well, especially if lazy loading is used.

### Client Side Caching / Async State Store

Another performance improvement would be the use of a client side async store. [React Query](https://tanstack.com/query/v3/) is an awesome solution for this but there are other options as well.

### Devops (Github actions)

I have found it helpful for developer workflow / long term code consistency to automatically run Build / Linting / Testing / Preview deploys on PRs. One nice thing about using Vercel is the [option for preview deployments](https://vercel.com/docs/deployments/preview-deployments) with comments. It speeds up the PR review process if you can click an autogenerated link in the PR, and its nice to have PRs automatically blocked from merging when build / linting / tests fail.

### Developer UI Library

Another thing that would help for development in the repository is a UI Library display like [Storybook](https://storybook.js.org/). This would especially be helpful if an internal UI library is developed and MUI is refactored out.

### Faster Package Manager

It would be nice for development if a faster package manager was used like [yarn](https://yarnpkg.com/) or [pnpm](https://pnpm.io/).

### Type-safe / Build Validated Env Variables

It would be great if build failed for missing environment variables. Also it would be nice if environment variables had better type safety, one package that can help with this is [T3 Env](https://env.t3.gg/).

**Comment by fercevik729** [comment]
## Next.js Refactoring
We've actually been using Next.js v13 and the app router since day 1, although we haven't been taking full advantage of it with RSC's, Route Handlers, due to the significant learning curve associated with using such features. Also a lot of libraries like NextAuth don't have stable support for the app router (but they hopefully will soon with v5). However, we do plan on making extensive use of server components, route handlers, and server actions going forward. This is in part due to our dissatisfaction with GraphQL and TypeGraphQL, as well as rendering and performance issues with using majority client-side components. This would also solve some security problems.

## MUI -> ShadCN + Storybook
This is a big migration, but we can go about doing this incrementally if there are people willing to do so. However, like you said this would require maintaining components and ensuring responsiveness which MUI already takes care of. For now I'd like to hold off on starting this task until we move some components to the server, and see if the change is necessary, i.e. initial bundles are still too big and slow to load. As for UI testing, we've kind of taken a manual testing approach so Storybook could be a good addition, but I worry that it might take up some time. I'd be happy to experiment with it though for some of our existing reusable components and if people find it to be helpful and not too cumbersome to work with we can make it a standard.

## Loading States
By moving to server components and react query (see below), we will be able to make better loading states that don't flicker and enhance the UX.

## React Query
We do plan on using this as a replacement for Apollo Client and GraphQL. Possibly in conjunction with a state management library like Zustand to clean up some of the providers.

## Responsive layouts
This can definitely be improved upon significantly. I had planned to make the search and progress sidebars collapsible as well to support devices even smaller than tablets. All suggestions are welcome here.

## Developer workflow
These are good suggestions and the build/linting workflows can probably be set up pretty quickly. We currently have Vercel Previews and GitHooks so be sure to use those as well!

## Faster package manager
Good idea. I've been using yarn for personal projects, and like it more than npm. Also it doesn't have the security issues that npm does.

## Type-safe env
Great suggestion. This has cost me a lot of time in 115A, so we can definitely implement this.
